modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="kinematica"
version="0.1.4-ALPHA"
displayName="Kinematica"
displayURL=""
updateJSONURL=""
credits="Smileycorp"
authors="Smileycorp"
description=""

[[dependencies.kinematica]]
    modId="atlaslib"
    mandatory=true
    versionRange="[1.1.3,)"
    ordering="NONE"
    side="BOTH"